services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    ports:
      - '8090:8090'
    environment:
      - PB_ADMIN_EMAIL=admin@dartscore.fr
      - PB_ADMIN_PASSWORD=password
      - TZ=Europe/Paris
    volumes:
      - pb_data:/pb/pb_data
    restart: unless-stopped

  dartscore:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_DB=pocketbase
        - VITE_PB_URL=http://localhost:8090
    ports:
      - '80:80'
    depends_on:
      - pocketbase
    restart: unless-stopped

volumes:
  pb_data:
